apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: sippy
  strategy:
    activeDeadlineSeconds: 21600
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: sippy
    spec:
      containers:
      - image: docker.io/openshift/sippy
        imagePullPolicy: Always
        name: sippy
        ports:
        - name: www
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 2112
          protocol: TCP
        resources:
          limits:
            memory: 3G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/sippy
        args:
        - --local-data
        - /data
        - --release
        - "4.13"
        - --release
        - "4.12"
        - --release
        - "4.11"
        - --release
        - "4.10"
        - --release
        - "4.9"
        - --release
        - "4.8"
        - --release
        - "4.7"
        - --release
        - "4.6"
        - --release
        - "3.11"
        - --server
        env:
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
        volumeMounts:
        - mountPath: /data
          name: data
      - image: quay.io/enterprisedb/postgresql
        imagePullPolicy: Always
        name: postgres
        resources:
          limits:
            memory: 2G
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db
      - image: docker.io/openshift/sippy
        imagePullPolicy: Always
        name: fetchdata
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 3G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/fetchdata.sh
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/bigquery/credentials
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/bigquery
          name: bigquery-credentials
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sippy
      - name: db
        persistentVolumeClaim:
          claimName: sippy-db
      - name: bigquery-credentials
        secret:
          secretName: bigquery-credentials
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sippy
      - fetchdata
      from:
        kind: ImageStreamTag
        name: sippy:latest
        namespace: bparees
    type: ImageChange
