apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: sippy
  strategy:
    activeDeadlineSeconds: 21600
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: sippy
    spec:
      containers:      
      - image: docker.io/bparees/sippy
        imagePullPolicy: Always
        name: sippy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /tmp/src/sippy
        args:
        - --local-data
        - /data
        - --release
        - "4.5"
        - --release
        - "4.4"
        - --release
        - "4.3"
        - --release
        - "4.2"
        - --lookback
        - "7"
        - --server
        volumeMounts:
        - mountPath: /data
          name: data
      - image: docker.io/bparees/sippy
        imagePullPolicy: Always
        name: fetchdata
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /tmp/src/scripts/fetchdata.sh
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sippy
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sippy
      - fetchdata
      from:
        kind: ImageStreamTag
        name: sippy:latest
        namespace: bparees
    type: ImageChange
