prow:
  url: https://prow.ci.openshift.org/prowjobs.js
releases:
  "4.20":
    jobs:
      periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-ovn-serial-2of2: true
      periodic-ci-openshift-release-main-ci-4.20-e2e-azure-ovn-upgrade: true
      periodic-ci-openshift-release-master-nightly-4.20-e2e-gcp-ovn-csi: true
