prow:
  url: https://prow.ci.openshift.org/prowjobs.js
releases:
  "4.13":
    jobs:
      periodic-ci-openshift-release-master-nightly-4.13-e2e-aws-sdn-serial: true
      periodic-ci-openshift-release-master-ci-4.13-e2e-azure-ovn-upgrade: true
      periodic-ci-openshift-release-master-nightly-4.13-e2e-gcp-sdn: true
